### PR TITLE
chore: Adding `auto_delete` to ecr repositories

### PR DESCRIPTION
**Pull request by malachi-constant**
**Dependencies**
- [X] Modules must be updated to `aws-cdk-lib=2.70.0` to use `auto_delete_images`

*Description of changes:*
Adding `auto_delete` to ecr repositories

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by malachi-constant** [comment]
@dgraeber @srinivasreddych We'll need to get these modules to `>=2.70.0` before merging this in.

**Comment by srinivasreddych** [comment]
@malachi-constant Pls check the linting errors above. Sure, i will be bringing in the version upgrades we've made internally (2.70.0) and then its safe to merge this PR. Until then, i will be converting the PR to `draft`

**Comment by malachi-constant** [comment]
> @malachi-constant Pls check the linting errors. Sure, i will be bringing in the version upgrades we've made internally (2.70.0) and then its safe to merge this PR. Until then, i will be converting the PR to `draft`

The linting errors are directly due to `mypy` checks which is caused by the lower version of the CDK. So those will resolve once upgraded.

**Comment by srinivasreddych** [comment]
> > @malachi-constant Pls check the linting errors. Sure, i will be bringing in the version upgrades we've made internally (2.70.0) and then its safe to merge this PR. Until then, i will be converting the PR to `draft`
> 
> The linting errors are directly due to `mypy` checks which is caused by the lower version of the CDK. So those will resolve once upgraded.

Makes complete sense. Thanks

**Comment by srinivasreddych** [comment]
Thanks for the PR!

**Review by dgraeber — APPROVED** [review]

**Pull request merged**
