### PR TITLE
removing needless modules for AV/ADAS Solutions sonar scan

### PR DESCRIPTION
**Pull request by srinivasreddych**
*Issue #, if available:*

*Description of changes:*
removing needless modules for AV/ADAS Solutions sonar scan

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by dgraeber — CHANGES_REQUESTED** [review]
I believe that the core/metadata-storage module is still needed....we are only using one of the tables and not the glue table, but it is needed:

`name: metadata-storage
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/core/metadata-storage/?ref=release/2.0.0
`

**Comment by srinivasreddych** [comment]
> metadata-storage

Thanks for catching it!

**Review by dgraeber — CHANGES_REQUESTED** [review]
OpenSearch Proxy is deleted...it is needed

**Review by dgraeber — CHANGES_REQUESTED** [review]
lande detection is still needed (post-processing)?

**Comment by srinivasreddych** [comment]
Can you check now? I addressed all of em

**Review by dgraeber — APPROVED** [review]

**Pull request merged**
