### PR TITLE
Add LaneDet to Dag and Generalize Pipeline for Ford dataset support

### PR DESCRIPTION
**Pull request by kevinsoucy**
*Issue #, if available:*

*Description of changes:*
- Add LaneDet step to Image Pipeline
- Generalize pipeline to support both VSI data and Ford public datasets

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by dgraeber — COMMENTED** [review]
This looks good.  Where is the CHANGELOG update?

**Review by chamcca — APPROVED** [review]
pending @dgraeber's comments, approved

**Comment by dgraeber** [comment]
Need to run `./scripts/fix.sh --language python --path modules/post-processing/lane-detection/ `

**Comment by chamcca** [comment]
@kevinsoucy and @dgraeber  this PR is still waiting on an update and static checks. is it still needed?

**Comment by dgraeber** [comment]
@chamcca yes...this PR needed.  This issue arose as a by-product of when we turned on static checks in the repo and had to modify the NagSuppression objects.  It is an easy fix, but due to timing of other pending issues, it was sidelined.

@kevinsoucy lets get together when you have a minute and we can get this PR completed

**Comment by dgraeber** [comment]
There are 4 modules that need to be formatted prior to pushing.  Run the following commands from the root of the project:

```
scripts/fix.sh --language python --path modules/analysis/rosbag-image-pipeline/
scripts/fix.sh --language python --path modules/post-processing/yolo-object-detection/
scripts/fix.sh --language python --path modules/post-processing/lane-detection/
scripts/fix.sh --language python --path modules/post-processing/yolop-lane-detection/
```

**Review by dgraeber — APPROVED** [review]

**Pull request merged**
