### PR TITLE
adding event bus to module for reuse

### PR DESCRIPTION
**Pull request by dgraeber**
Adding an event bus creation to `metadata-storage` so all modules can leverage

### CODE REVIEW

**Comment by srinivasreddych** [comment]
With a custom-bus, we cannot run cron based events using event-bridge currently!

**Comment by srinivasreddych** [comment]
Closing it for now and will use it when there is a need for an `ADDF` specific event bus

**Comment by a13zen** [comment]
There is a need for an ADDF specific event bus for orchestration. For instance, after we extract the images and signal data and run object detection, we could publish an event that triggers downstream workflows like scene detection or signal sychronization

**Comment by a13zen** [comment]
However, for triggering Step Functions on a time based rule, we don't need the bus. We only need the EventBridge Rule that runs based on a cron schedule that triggers the event which triggers Step Functions
https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html

These are two use cases then:
1. Time based cron expression Rule -> Trigger single event rule -> Trigger targeted workflow
2. Event Bus based Event ->  Trigger all subscribed rules -> Trigger downstream workflows (possibly cross account/region too)

**Pull request closed without merging**
