### PR TITLE
Adding ADDF WebApp Wireframes based on Sketch

### PR DESCRIPTION
**Pull request by cro13**
*Issue #, if available: * https://github.com/awslabs/autonomous-driving-data-framework/issues/114

*Description of changes:*  Added WebApp Wireframes using Sketch.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by JunjieTang-D1** [comment]
please remove the aws logo. This will need additional approval of marketing. This will be done in Q1 2023.

**Comment by cro13** [comment]
> please remove the aws logo. This will need additional approval of marketing. This will be done in Q1 2023.

done

**Comment by dgraeber** [comment]
I have a some suggestions:

1. Please put this on a WIP branch rather than `main` for now (as-is). These are wireframes and don't really fit into the scheme at the moment.  Also, most likely the UI / Webapp will be deployed as a module, so we should fine a home that fits the structure
2. Please remove all spaces (' ') from any names prior to committing.  Use an underscore ('_') instead?


Please reach out if this doesn't make sense.

**Review by JunjieTang-D1 — APPROVED** [review]

**Comment by cro13** [comment]
> I have a some suggestions:
> 
> 1. Please put this on a WIP branch rather than `main` for now (as-is). These are wireframes and don't really fit into the scheme at the moment.  Also, most likely the UI / Webapp will be deployed as a module, so we should fine a home that fits the structure
> 2. Please remove all spaces (' ') from any names prior to committing.  Use an underscore ('_') instead?
> 
> Please reach out if this doesn't make sense.

> 

I think once we have the webapp modules coming into place, it will go in the direction of a separate repo, otherwise this will be a huge monorepo. As a first step, I think we can keep the wireframes here.
The names can be changed easily, no problem.

**Pull request merged**
